name:                csgo-analysis
version:             0.1.0.0
github:              "BorisNikulin/csgo-analysis"
license:             BSD3
author:              "Boris Nikulin"
maintainer:          "NikulinBE@gmail.com"
copyright:           "2018 Boris Nikulin"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/BorisNikulin/csgo-analysis#readme>

data-files: data/**/*

dependencies:
    - base >= 4.7 && < 5
    - text >= 1.2 && < 2
    - scalpel-core < 1
    - time >= 1 && < 2
    - sqlite-simple >= 0.4 && < 1
    - directory >= 1.3 && < 2
    - async >= 2 && < 3

library:
  source-dirs: src
  ghc-options:
      - -fno-warn-tabs

executables:
  scraper-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
        - -threaded
        - -rtsopts
        - -with-rtsopts=-N
        - -fno-warn-tabs
    dependencies:
        - csgo-analysis
