name:                csgo-analysis
version:             0.1.0.0
github:              "BorisNikulin/csgo-analysis"
license:             BSD3
author:              "Boris Nikulin"
maintainer:          "NikulinBE@gmail.com"
copyright:           "2018 Boris Nikulin"

extra-source-files:
    - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/BorisNikulin/csgo-analysis#readme>

dependencies:
    - base >= 4.7 && < 5
    - tagsoup < 1
    - sqlite-simple >= 0.4 && < 1

library:
  source-dirs: src

executables:
  csgo-analysis-scraper-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
        - -threaded
        - -rtsopts
        - -with-rtsopts=-N
    dependencies:
        - csgo-analysis
